### ISSUE TITLE
PHP_SELF

### ISSUE THREAD

**Issue by tbba** [teppokoivula/ProcessChangelog#12]
Hi Teppo, there is that old code snippet you use:
  // IIS support, based on http://davidwalsh.name/iis-php-server-request_uri
    $_SERVER['REQUEST_URI'] = substr($_SERVER['PHP_SELF'], 1) . $qs;

I am wondering whether PHP_SELF isn't also vulnerable and should be filtered with htmlspecialchars or replaced by SCRIPT_NAME maybe?

**Comment by teppokoivula** [comment]
Sorry, @tbba. I took a look at this back in July and decided this was not an issue, but it looks like I never mentioned it here or closed the issue. Doing a bit of cleanup here right now and this came up again :)

To summarize, I don't think that this is actually a problem: the URL *should* be captured and stored as-is, that's intentional, and it is already escaped when it is displayed on the built-in admin changelog page.

If one creates a custom view for displaying changelog data and doesn't properly escape content, it's true that this could become an issue. In my opinion that's still not something that this module should force on the user. As far as I know, not escaping data might as well be an intentional choice.

Thanks for your concern, and please let me know if I'm missing something important here :)
