### ISSUE TITLE
Hiding and unhiding a page is recorded as publishing a page

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#18]
Title says it all - if you hide or unhide a page, in both cases, you get "pubished" in the "what" column.

**Comment by teppokoivula** [comment]
Hey @adrianbj, thanks for the report! This should be fixed with version 1.6.0. Would be great if you could test and confirm :)

This fix involved adding two new tracked events, "hid" and "unhid", so if you want to track these you'll have to visit the Changelog Hooks module settings and check those in the operations list.

**Comment by adrianbj** [comment]
@teppokoivula - looks good so far - thanks!
