### ISSUE TITLE
Remove processwire dependency from composer.json

### ISSUE THREAD

**Issue by uiii** [teppokoivula/ProcessChangelog#29]
Hi, I don't think it is a good idea to have processwire dependecy in composer.json, it happens that site loads the files from here instead of regular `wire` folder. If you need it for development, add it to `require-dev` section.

**Comment by teppokoivula** [comment]
Thanks @uiii, I think you're right.

Can't remember for sure anymore, but the original intention might've been just to signal that the module requires (specified version of) ProcessWire. In my case ProcessWire core files are intentionally loaded from the vendor directory, so that likely explains why this hasn't come up before.

Will test a bit and then remove the dependency, unless there's something I'm forgetting/missing now 🙂

**Comment by uiii** [comment]
Hi Tepoo, how does it look? I am starting to get another problem with this (errors about redeclaring a class).

**Comment by teppokoivula** [comment]
Thanks for the reminder. Haven't had time to properly test this, but this shouldn't cause any issues, so I've gone ahead and removed that dependency.

**Comment by uiii** [comment]
thanks
