### ISSUE TITLE
Feature request: view link

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#32]
Hi @teppokoivula - I think I have asked this before and I am not sure you were interested in adding it, but I find myself wanting it often many times a day as I check on what site editors have changed.

I have added this after line 820:
```
            if ($page->viewable()) {
                $target .= " &nbsp; <a class='action view-page' href='{$page->url}'>"
                    . "<span class='visual-label' aria-hidden='true'>" . $this->_('view page') . "</span>"
                    . "<span class='visually-hidden'>" . sprintf($this->_('View page: %s'), $page->name) . "</span>"
                    . "</a>";
            }
```

Thanks very much for considering it.

**Comment by teppokoivula** [comment]
Thanks for the suggestion, Adrian. Makes sense to me, included in latest versions.

Only reason I can think of why this might be problematic is related to available space in the table, but that's an issue that needs to be solved either way. Currently the changelog table doesn't look particularly nice on smaller screens :)

**Comment by adrianbj** [comment]
@teppokoivula - what about edit, view, and trash icons instead of the text links? Or at least remove the "page" from "edit page" and "view page" ?

**Comment by teppokoivula** [comment]
@adrianbj:

- Icons might make sense, but generally I tend to prefer a descriptive message instead of icon which may or may not be obvious (without viewing a tooltip). They are more understandable to "returning users", so perhaps not such a big deal here, though.
- I did consider "view" without "page", but at least to me it was not obvious: there's also a "delete" link, so it's slightly confusing when "view" and "edit" apply to the page, while "delete" applies to the log row.

Anyway, good suggestions, and something to keep in mind in future updates. I'd definitely like to make some changes to the GUI one of these days.
