### ISSUE TITLE
Undefined array key "Previous page URL" in /site/modules/ProcessChangelog/ProcessChangelog.module:939

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#35]
Hi @teppokoivula 

I just came across this error - not sure what triggered it exactly, but hopefully it will be obvious enough to you the reason for it.

Let me know if you need me to do some additional digging. Thanks!

**Comment by adrianbj** [comment]
Just saw this again when viewing /changelog/rss

**Comment by teppokoivula** [comment]
Hey @adrianbj — sorry for the delay, had completely forgotten this issue.

This should be fixed with the latest version, but please let me know if the issue still persists. In case of multi-lingual sites page names were sometimes handled incorrectly while logging rename operation. I'm guessing that this might have been your issue as well, though I've also added a separate check to avoid notice in case URL is missing for some other reason.
